In [8]:
import mlx.core as mx

# manually set seed
mx.random.seed(42)

A = mx.random.normal((1, 3, 32, 32))
print(f"A.shape: {A.shape}")

# Remove the 1 dimension
print(A.squeeze(axis=0).shape)

print(A.squeeze().shape)

A.shape: (1, 3, 32, 32)
(3, 32, 32)
(3, 32, 32)


In [16]:
# Generating a range
# similar to torch.arange
x = mx.arange(-10., 10., 1.0)
x

array([-10, -9, -8, ..., 7, 8, 9], dtype=float32)

In [18]:
# Weigth matrix
W = mx.random.normal((1, 2))
W, W.shape

(array([[0.506034, 0.100576]], dtype=float32), (1, 2))

In [23]:
# toy input
X = mx.array([1.2, 3.4])
X.shape

(2,)

In [24]:
# bias in linear model
b = mx.random.uniform(0., 1.0, shape=[1])
b, b.shape

(array([0.671694], dtype=float32), (1,))

In [31]:
# y = W * T + b
y = W @ X + b
y

array([1.6209], dtype=float32)

In [32]:
# y = X * WT + b
y2 = X @ W.T + b
y2

array([1.6209], dtype=float32)

In [33]:
import mlx.nn as nn

y_actual = mx.array([0.1])
l1 = nn.losses.l1_loss(y, y_actual)
l1

array(1.5209, dtype=float32)

In [35]:
# Update weights, naively
W = W - l1 * 0.01
W

array([[0.475617, 0.0701584]], dtype=float32)

In [36]:
# Repeat prediction
y = W @ X + b
y

array([1.48097], dtype=float32)

In [37]:
# Repeat loss computation
l1 = nn.losses.l1_loss(y, y_actual)
l1

array(1.38097, dtype=float32)

In [38]:
# Repeat weights update, oh well...
W = W - l1 * 0.01
W

array([[0.461807, 0.0563487]], dtype=float32)

In [39]:
y = W @ X + b
y

array([1.41745], dtype=float32)